package subtitle

import (
	"strings"
	"testing"
)

func TestMatch(t *testing.T) {
	cases := []struct {
		base, name string
		wantLang   string
		wantOK     bool
	}{
		{"Movie", "Movie.srt", "", true},
		{"Movie", "Movie.en.srt", "en", true},
		{"Movie", "Movie.en.forced.srt", "en", true},
		{"Movie", "Other.srt", "", false},
		{"Movie", "Movie.txt", "", false}, // only .srt
	}
	for _, c := range cases {
		lang, ok := Match(c.base, c.name)
		if ok != c.wantOK || lang != c.wantLang {
			t.Errorf("Match(%q,%q) = (%q,%v), want (%q,%v)", c.base, c.name, lang, ok, c.wantLang, c.wantOK)
		}
	}
}

func TestSidecars(t *testing.T) {
	names := []string{"Movie.mkv", "Movie.srt", "Movie.de.srt", "Unrelated.srt"}
	subs := Sidecars(names, "Movie")
	if len(subs) != 2 {
		t.Fatalf("got %d sidecars, want 2: %+v", len(subs), subs)
	}
	if subs[0].Lang != "" || subs[1].Lang != "de" || subs[1].Label != "German" {
		t.Fatalf("unexpected sidecars: %+v", subs)
	}
}

func TestToVTT(t *testing.T) {
	srt := "1\n00:00:01,000 --> 00:00:04,000\nHello\n\n2\n00:00:05,500 --> 00:00:06,000\nWorld\n"
	var b strings.Builder
	if err := ToVTT(&b, strings.NewReader(srt)); err != nil {
		t.Fatal(err)
	}
	out := b.String()
	if !strings.HasPrefix(out, "WEBVTT\n\n") {
		t.Errorf("missing WEBVTT header:\n%s", out)
	}
	if strings.Contains(out, ",000") || strings.Contains(out, ",500") {
		t.Errorf("comma separators not rewritten:\n%s", out)
	}
	if !strings.Contains(out, "00:00:01.000 --> 00:00:04.000") {
		t.Errorf("timing line not converted:\n%s", out)
	}
	// The numeric cue index lines are dropped.
	if strings.Contains(out, "\n1\n") || strings.Contains(out, "\n2\n") {
		t.Errorf("cue index lines not dropped:\n%s", out)
	}
	if !strings.Contains(out, "Hello") || !strings.Contains(out, "World") {
		t.Errorf("cue text lost:\n%s", out)
	}
}

// assSample is an Aegisub-style script of the shape that turns up under an ".srt" name:
// a header section, styles, then [Events] with override tags and "\N" line breaks.
const assSample = "\ufeff[Script Info]\r\n" +
	"; Script generated by Aegisub 2.1.7\r\n" +
	"ScriptType: v4.00+\r\n" +
	"\r\n" +
	"[V4+ Styles]\r\n" +
	"Format: Name, Fontname, Fontsize\r\n" +
	"Style: Default,Arial,28\r\n" +
	"\r\n" +
	"[Events]\r\n" +
	"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n" +
	"Dialogue: 0,0:02:21.51,0:02:29.57,Default,,0000,0000,0000,,{\\i1}Once in a millennium,{\\i0}\\Na time of life comes around...\r\n" +
	"Comment: 0,0:00:01.00,0:00:02.00,Default,,0000,0000,0000,,not rendered\r\n" +
	"Dialogue: 0,0:00:05.00,0:00:06.25,Default,,0000,0000,0000,,Earlier line, with a comma\r\n"

func TestIsASS(t *testing.T) {
	if !IsASS([]byte(assSample)) {
		t.Error("Aegisub script not detected as ASS")
	}
	srt := "1\n00:00:01,000 --> 00:00:04,000\nHello\n"
	if IsASS([]byte(srt)) {
		t.Error("SRT misdetected as ASS")
	}
}

// TestToVTTFromASS is the regression for ASS content arriving under an ".srt" name: it used
// to pass through as a cue-less WebVTT file, so the track listed but nothing was drawn.
func TestToVTTFromASS(t *testing.T) {
	var b strings.Builder
	if err := ToVTT(&b, strings.NewReader(assSample)); err != nil {
		t.Fatal(err)
	}
	out := b.String()
	if !strings.HasPrefix(out, "WEBVTT\n\n") {
		t.Errorf("missing WEBVTT header:\n%s", out)
	}
	if n := strings.Count(out, "-->"); n != 2 {
		t.Errorf("got %d cues, want 2 (Comment: lines are not cues):\n%s", n, out)
	}
	if strings.Contains(out, "not rendered") {
		t.Errorf("Comment: line emitted as a cue:\n%s", out)
	}
	// Cues are emitted in start order, not file order.
	if strings.Index(out, "00:00:05.000") > strings.Index(out, "00:02:21.510") {
		t.Errorf("cues not sorted by start time:\n%s", out)
	}
	if !strings.Contains(out, "00:02:21.510 --> 00:02:29.570") {
		t.Errorf("centisecond timestamp not converted:\n%s", out)
	}
	if strings.Contains(out, "{") || strings.Contains(out, `\i1`) {
		t.Errorf("override blocks not stripped:\n%s", out)
	}
	if !strings.Contains(out, "Once in a millennium,\na time of life comes around...") {
		t.Errorf(`\N not expanded to a line break:`+"\n%s", out)
	}
	// The Text field keeps its own commas rather than being split on them.
	if !strings.Contains(out, "Earlier line, with a comma") {
		t.Errorf("cue text truncated at a comma:\n%s", out)
	}
	if strings.Contains(out, "[Script Info]") || strings.Contains(out, "Style: Default") {
		t.Errorf("script header leaked into the output:\n%s", out)
	}
}

func TestAssTextEscapesMarkup(t *testing.T) {
	got := assText(`{\an8}5 &lt; 10 <b>x</b>\hy`)
	want := "5 &amp;lt; 10 &lt;b&gt;x&lt;/b&gt; y"
	if got != want {
		t.Errorf("assText = %q, want %q", got, want)
	}
}

func TestAssFormatCustomOrder(t *testing.T) {
	start, end, text, fields := assFormat("Marked, Start, End, Style, Text")
	if start != 1 || end != 2 || text != 4 || fields != 5 {
		t.Errorf("assFormat = (%d,%d,%d,%d), want (1,2,4,5)", start, end, text, fields)
	}
	// A list without Start/End is unusable and falls back to the default order.
	if s, e, tx, f := assFormat("Foo, Bar"); s != 1 || e != 2 || tx != 9 || f != 10 {
		t.Errorf("fallback = (%d,%d,%d,%d), want (1,2,9,10)", s, e, tx, f)
	}
}

func TestLabel(t *testing.T) {
	if Label("en") != "English" {
		t.Errorf("Label(en) = %q", Label("en"))
	}
	if Label("xx") != "XX" { // unknown falls back to uppercased tag
		t.Errorf("Label(xx) = %q", Label("xx"))
	}
}
